name: CI

on: [push,pull_request]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: slightly-open/enrich-env@master
    - run: printenv
      
    - uses: slightly-open/enrich-env@master
      with:
        prefix_env: MY_
    - run: printenv
    
