name: CI

on: [push,pull_request]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - name: Checkout
      uses: actions/checkout@v2

    - uses: ./ # Uses an action in the root directory
    - run: printenv | sort

    - uses: ./ # Uses an action in the root directory
      with:
        prefix_env: MY_
    - run: printenv | sort

