name: CI

on: [push,pull_request]

jobs:
  enrich:

    runs-on: ubuntu-latest

    steps:
    - name: Checkout
      uses: actions/checkout@v2

    - uses: ./ # Uses an action in the root directory
      with:
        github-token: ${{ github.token }}
    - run: printenv | sort

